# site settings
title: MAgPIE
subtitle: modeling global land systems
creator: Potsdam Institute for Climate Impact Research (PIK) 
email: magpie@pik-potsdam.de
description: A modular open-source framework for modeling global land systems
baseurl: ""
url: # the base hostname & protocol for your site
author:
street_address: Telegrafenberg A 31
city: Potsdam
state: Brandenburg
zip_code: 14473
country: Germany
phone:

plugins:
  - jekyll-redirect-from

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

collections:
  events:
    output: true
    title: Events
  tutorials:
    output: true
    permalink: /:collection/:name
    title: Tutorials
    sort_by: lesson
  showcases:
    output: true
    permalink: /showcase/:name
    title: Showcase
  workshops:
    output: true
    title: Workshop
    

# social settings (key must match name of font awesome icon)
# see Https://Fontawesome.Com/Icons?D=Gallery&P=2&S=Brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  envelope: mailto:magpie@pik-potsdam.de
  home: https://www.pik-potsdam.de/en/institute/departments/transformation-pathways/research/landuse
  github: https://github.com/magpiemodel/magpie
  wikipedia-w: https://en.wikipedia.org/wiki/MAgPIE
  book: https://rse.pik-potsdam.de/doc/magpie/4.8.2
 
# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
